management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        url: http://opentelemetry-collector.monitoring:4318/v1/metrics
        step: 30s
app:
  data:
    default data from application yaml
